/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package internalassesment;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;

/**
 *
 * @author l.mccausland
 */
public class MainScreen extends javax.swing.JFrame {

    public boolean trigger;
    public int quizCount;
    public int quizOffset;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        setFrame();
        setLabel();
        sideButtons(quizesLabel);
        sideButtons(settingsLabel);
        setButtons(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeLabel = new javax.swing.JLabel();
        quizesLabel = new javax.swing.JLabel();
        settingsLabel = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        quitLabel = new javax.swing.JLabel();
        sideBarLabel = new javax.swing.JLabel();
        topBarLabel = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        homeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/home.png"))); // NOI18N
        getContentPane().add(homeLabel);
        homeLabel.setBounds(25, 170, 30, 30);

        quizesLabel.setText("                   View Quizes");
        quizesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quizesLabelMouseClicked(evt);
            }
        });
        getContentPane().add(quizesLabel);
        quizesLabel.setBounds(0, 160, 180, 50);

        settingsLabel.setText("                   Settings");
        settingsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsLabelMouseClicked(evt);
            }
        });
        getContentPane().add(settingsLabel);
        settingsLabel.setBounds(0, 210, 180, 50);

        title.setText("Quiza");
        getContentPane().add(title);
        title.setBounds(40, 10, 200, 60);

        quitLabel.setForeground(new java.awt.Color(51, 51, 51));
        quitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/xButton.png"))); // NOI18N
        quitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitLabelMouseClicked(evt);
            }
        });
        getContentPane().add(quitLabel);
        quitLabel.setBounds(800, 20, 40, 40);

        sideBarLabel.setBackground(new java.awt.Color(102, 153, 255));
        sideBarLabel.setOpaque(true);
        getContentPane().add(sideBarLabel);
        sideBarLabel.setBounds(0, 0, 180, 690);

        topBarLabel.setBackground(new java.awt.Color(51, 51, 51));
        topBarLabel.setOpaque(true);
        getContentPane().add(topBarLabel);
        topBarLabel.setBounds(180, 0, 700, 80);

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createButton);
        createButton.setBounds(190, 90, 72, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_quitLabelMouseClicked

    private void quizesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quizesLabelMouseClicked
        onClick(quizesLabel);
    }//GEN-LAST:event_quizesLabelMouseClicked

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String name = JOptionPane.showInputDialog("Enter quiz name: ");
        JLabel newQuiz = new JLabel(name);
        newQuiz.setLocation(190, quizOffset + 130);
        newQuiz.setSize(650, 30);
        Border blackline = BorderFactory.createLineBorder(Color.black);
        newQuiz.setBorder(blackline);
        newQuiz.setVisible(true);
        add(newQuiz);

        JButton newButton = new JButton("Options");
        newButton.setLocation(800, quizOffset + 130);
        newButton.setSize(30, 30);
        newButton.setVisible(true);
        add(newButton);

        SwingUtilities.updateComponentTreeUI(this);
        setLabel();
        quizOffset += 35;
        quizCount++;
    }//GEN-LAST:event_createButtonActionPerformed

    private void settingsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsLabelMouseClicked
        onClick(settingsLabel);
    }//GEN-LAST:event_settingsLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainScreen().setVisible(true);
        });
    }

    /**
     * sets components of the jframe
     */
    private void setFrame() {
        this.setTitle("Quiza");
        this.setSize(880, 525);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JLabel quitLabel;
    private javax.swing.JLabel quizesLabel;
    private javax.swing.JLabel settingsLabel;
    private javax.swing.JLabel sideBarLabel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel topBarLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * sets the visual appearance of the labels;
     */
    private void setLabel() {
        // set Image Icon for the quit button

        // create new Image Icon variable
        ImageIcon quitIcon;
        // set the icon variable to the desired image
        quitIcon = new ImageIcon(getClass().getResource("/pictures/xButton.png"));
        // convert it into an image
        Image quitImg = quitIcon.getImage();
        // set the scale of the image to the label it fits
        Image quitImgScale = quitImg.getScaledInstance(quitLabel.getWidth(), quitLabel.getHeight(), Image.SCALE_SMOOTH);
        // created the scaled version of the icon
        ImageIcon quitScaledIcon = new ImageIcon(quitImgScale);
        // set the label icon to the scaled version
        quitLabel.setIcon(quitScaledIcon);
        // set the label opaque
        quitLabel.setOpaque(true);
        // set the background of the label to match the background of the button;
        quitLabel.setBackground(topBarLabel.getBackground());
        // add it to the frame
        add(quitLabel);

        // set Image Icon for the home icon
        ImageIcon homeIcon;
        homeIcon = new ImageIcon(getClass().getResource("/pictures/home.png"));
        Image img = homeIcon.getImage();
        Image imgScale = img.getScaledInstance(homeLabel.getWidth(), homeLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        homeLabel.setIcon(scaledIcon);
        homeLabel.setOpaque(false);
        homeLabel.setBackground(sideBarLabel.getBackground());
        add(homeLabel);

        //change title text
        title.setFont(new Font("SansSerif", Font.PLAIN, 24));

    }

    private void setButtons(boolean bool) {
        createButton.setVisible(bool);
    }

    private void sideButtons(JLabel label) {
        label.setFont(new Font("SansSerif", Font.PLAIN, 14));
    }

    private void onClick(JLabel label) {
        if (!trigger) {
            label.setBackground(Color.WHITE);
            label.setOpaque(true);
            label.repaint();

            setButtons(true);

            trigger = true;
        } else if (trigger) {
            label.setOpaque(false);
            label.repaint();
            trigger = false;
            setButtons(false);
        }
        setLabel();
    }
}
